# Generated by Django 4.1.4 on 2023-01-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="categoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resId", models.CharField(max_length=3)),
                ("category", models.CharField(max_length=15)),
                ("catImage", models.ImageField(default="default.png", upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="menuModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resId", models.CharField(max_length=3)),
                ("category", models.CharField(max_length=15)),
                ("foodName", models.CharField(max_length=25)),
                (
                    "description",
                    models.CharField(default="Street Food, Gujarati", max_length=50),
                ),
                ("price", models.IntegerField()),
                ("ratings", models.IntegerField(default=0)),
                ("counter", models.IntegerField(default=0)),
                ("image", models.ImageField(default="default.png", upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="orderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userId", models.IntegerField(default=1)),
                ("foodId", models.IntegerField(default=1)),
                ("resId", models.CharField(max_length=3)),
                ("quantity", models.IntegerField(default=1)),
                ("status", models.BooleanField(default=False)),
                ("price", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="restaurantModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("manager", models.CharField(max_length=25)),
                ("contact", models.CharField(max_length=12)),
                ("email", models.EmailField(max_length=35)),
                ("social", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
