# Generated by Django 4.1.4 on 2023-01-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="resId",
            field=models.CharField(default=1, max_length=3),
        ),
    ]
